//Question 20 Think of something you could store in a Aray;

let countries = ["USA", "Canada", "Australia", "Japan", "Brazil"];
let mountains = ["Mount Everest", "K2", "Kangchenjunga", "Lhotse", "Makalu"];
let rivers = ["Nile", "Amazon", "Mississippi", "Yangtze", "Ganges"];
console.log("List of countries:", countries);
console.log("List of mountains:", mountains);
console.log("List of rivers:", rivers);