//Question 25 alien color#1:
//Question 26 alien color#2:
//Question 27 alien color#3:

// Exercise 25: Alien Colors #1
let alien_color_pass = 'green';
if (alien_color_pass === 'green') {
    console.log("Congratulations! You just earned 5 points.");
}
let alien_color_fail = 'yellow';
if (alien_color_fail === 'green') {
  
}
// Exercise 26: Alien Colors #2
let alien_color_if = 'green';
if (alien_color_if === 'green') {
    console.log("Congratulations! You just earned 5 points for shooting the alien.");
} else {
    console.log("Congratulations! You just earned 10 points.");
}

let alien_color_else = 'red'; 
if (alien_color_else === 'green') {
    console.log("Congratulations! You just earned 5 points for shooting the alien.");
} else {
    console.log("Congratulations! You just earned 10 points.");
}
// Exercise 27: Alien Colors #3
let alien_color_green = 'green';
if (alien_color_green === 'green') {
    console.log("Congratulations! You just earned 5 points.");
} else if (alien_color_green === 'yellow') {
    console.log("Congratulations! You just earned 10 points.");
} else if (alien_color_green === 'red') {
    console.log("Congratulations! You just earned 15 points.");
}
let alien_color_yellow = 'yellow';
if (alien_color_yellow === 'green') {
    console.log("Congratulations! You just earned 5 points.");
} else if (alien_color_yellow === 'yellow') {
    console.log("Congratulations! You just earned 10 points.");
} else if (alien_color_yellow === 'red') {
    console.log("Congratulations! You just earned 15 points.");
}

let alien_color_red = 'red';
if (alien_color_red === 'green') {
    console.log("Congratulations! You just earned 5 points.");
} else if (alien_color_red === 'yellow') {
    console.log("Congratulations! You just earned 10 points.");
} else if (alien_color_red === 'red') {
    console.log("Congratulations! You just earned 15 points.");
}
